# Generated by Django 4.2.1 on 2023-05-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=320, null=True, unique=True),
        ),
    ]
