# Generated by Django 4.2.1 on 2023-05-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0005_alter_image_pereval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.CharField(max_length=320),
        ),
    ]
